name = mcl_inventory_tweaks
title = Inventory Tweaks for Mineclonia
description = Server-side inventory and storage sorting, Classic-style controls, protected slots, custom rules, safe bulk transfers and automatic replacement.
depends = mcl_inventory, mcl_player, mcl_formspec, mcl_util, mcl_chests, mcl_barrels, mcl_entity_invs, mcl_hunger, mcl_enchanting, mcl_potions, mcl_mobs, mcl_redstone
optional_depends = mcl_boats, mcl_minecarts, mcl_tools, mcl_gamemode
min_minetest_version = 5.17
textdomain = mcl_inventory_tweaks
